model_list:
  - model_name: ollama/llama3.2:latest
    litellm_params:
      model: ollama/llama3.2:latest
      api_base: http://localhost:11434

  - model_name: llama3.2
    litellm_params:
      model: ollama/llama3.2:latest
      api_base: http://localhost:11434

general_settings:
  master_key: sk-nutriplan-litellm-proxy-admin
  ui_username: admin
  ui_password: password123
