<script setup lang="ts">
const lastUpdated = 'August 27, 2026'
</script>

<template>
  <div class="max-w-4xl mx-auto px-6 py-20">
    <!-- Header -->
    <div class="mb-12 border-b border-border pb-8">
      <div class="inline-block text-[0.75rem] font-data font-bold uppercase tracking-[0.2em] text-primary mb-3">Legal &amp; User Agreement</div>
      <h1 class="font-display font-bold text-[2.4rem] md:text-[3rem] text-ink leading-tight mb-3">
        Terms of Service
      </h1>
      <p class="text-[0.88rem] text-ink-muted">
        Last updated: {{ lastUpdated }} · Agreement between User and NutriPlan AI, Inc.
      </p>
    </div>

    <!-- Content -->
    <div class="space-y-8 text-ink leading-relaxed text-[0.95rem]">
      <section class="space-y-3">
        <h2 class="font-display font-bold text-[1.3rem] text-ink">1. Acceptance of Terms</h2>
        <p class="text-ink-muted">
          By creating an account, accessing, or using NutriPlan AI, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not use our services.
        </p>
      </section>

      <!-- Critical Health Disclaimer -->
      <section class="p-6 rounded-2xl bg-amber-500/10 border border-amber-500/30 space-y-3">
        <h2 class="font-display font-bold text-[1.15rem] text-amber-900 flex items-center gap-2">
          <span>▲ Medical &amp; Clinical Nutrition Advice Disclaimer</span>
        </h2>
        <p class="text-amber-950/80 text-[0.9rem] leading-relaxed">
          NutriPlan AI provides automated computational nutrition planning grounded in ICMR-NIN science and educational wellness tracking. 
          <strong>NutriPlan AI is NOT a licensed hospital, primary care clinic, or emergency medical provider.</strong> 
          Recommendations generated by our solver do not constitute medical diagnoses. Always seek the guidance of your physician or registered clinical dietitian prior to initiating restrictive dietary protocols.
        </p>
      </section>

      <section class="space-y-3">
        <h2 class="font-display font-bold text-[1.3rem] text-ink">2. User Accounts &amp; Security</h2>
        <p class="text-ink-muted">
          You are responsible for maintaining the confidentiality of your login credentials. You agree to notify us immediately of any unauthorized access to your account. You must provide accurate demographic data to receive valid nutritional models.
        </p>
      </section>

      <section class="space-y-3">
        <h2 class="font-display font-bold text-[1.3rem] text-ink">3. Subscriptions, Free Trials, and Billing</h2>
        <p class="text-ink-muted">
          Paid plans (Pro Precision and Family Health) are billed on a recurring monthly or annual basis via Stripe.
        </p>
        <ul class="list-disc pl-6 space-y-2 text-ink-muted">
          <li><strong class="text-ink">Free Trials:</strong> 14-day trials grant complete access to Pro features. You will not be charged if you cancel before the trial concludes.</li>
          <li><strong class="text-ink">Cancellations:</strong> You can cancel subscription renewals at any time via Account Settings. Access persists until the end of the current billing cycle.</li>
          <li><strong class="text-ink">Refunds:</strong> We provide a 7-day money-back guarantee on all first-time subscription charges if you are unsatisfied with our service.</li>
        </ul>
      </section>

      <section class="space-y-3">
        <h2 class="font-display font-bold text-[1.3rem] text-ink">4. Expert Consultations</h2>
        <p class="text-ink-muted">
          Consultations booked through our Provider Hub connect you with independent certified nutritionists and dietitians. NutriPlan AI provides the encrypted WebRTC video interface, live SOAP note co-pilot, and scheduling infrastructure.
        </p>
      </section>

      <section class="space-y-3">
        <h2 class="font-display font-bold text-[1.3rem] text-ink">5. Limitation of Liability</h2>
        <p class="text-ink-muted">
          To the maximum extent permitted by applicable law, NutriPlan AI and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the platform.
        </p>
      </section>

      <section class="space-y-3">
        <h2 class="font-display font-bold text-[1.3rem] text-ink">6. Governing Law</h2>
        <p class="text-ink-muted">
          These Terms shall be governed and construed in accordance with the laws of the Republic of India, without regard to its conflict of law provisions.
        </p>
      </section>
    </div>
  </div>
</template>
