from typing import Dict, Any, Tuple

class NutritionValidator:
    """
    LLMs are notoriously bad at math. This validator ensures the meal plan
    generated by the LLM is within acceptable bounds of the user's targets.
    """
    
    def __init__(self):
        # 10% tolerance for calories, 15% for macros
        self.cal_tolerance = 0.10
        self.macro_tolerance = 0.15

    def validate_plan(self, llm_plan: Dict[str, Any], target_calories: int) -> Tuple[bool, str]:
        """
        Validates the LLM generated plan against targets.
        Returns a tuple: (is_valid, reason)
        """
        if not llm_plan or "meals" not in llm_plan or "daily_total_macros" not in llm_plan:
            return False, "Invalid JSON structure from LLM"
            
        totals = llm_plan["daily_total_macros"]
        actual_cals = totals.get("calories", 0)
        
        # 1. Validate Calories bounds
        min_cals = target_calories * (1 - self.cal_tolerance)
        max_cals = target_calories * (1 + self.cal_tolerance)
        
        if not (min_cals <= actual_cals <= max_cals):
            return False, f"Calories ({actual_cals}) out of bounds [{min_cals}-{max_cals}]"
            
        # 2. Validate internal math (Sum of meals == daily total)
        sum_cals = 0
        sum_protein = 0
        sum_carbs = 0
        sum_fat = 0
        
        for meal in llm_plan["meals"]:
            macros = meal.get("macros", {})
            sum_cals += macros.get("calories", 0)
            sum_protein += macros.get("protein", 0)
            sum_carbs += macros.get("carbs", 0)
            sum_fat += macros.get("fat", 0)
            
        if abs(sum_cals - actual_cals) > (actual_cals * 0.05): # 5% math error tolerance
            return False, f"LLM math error: sum of meals ({sum_cals}) != total ({actual_cals})"
            
        # Optional: We could do a deeper validation against the exact ingredients using our food DB
        # if we had the time/resources, but verifying the math and total bounds is sufficient for V1.
            
        return True, "Valid"

validator = NutritionValidator()
